# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 132f3964f7edb78ec66b703b2fade780b99f0df6f3bade0fb0037a0324e5a0300d4036289827fd27887731c47b397bf7780d3bf87fa8e5bc958022907de12587

test:
  secret_key_base: 0deba7ba954a32a4689d4bb2f83645c6dee3cd668840df0f52c490bc04b1ee59a4bb72bb93563045507b14270d3652b6011eca21eefc3f9cb4d26b8396c405ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
